import { NavigationLink as Link } from '@/components/ui/NavigationLink';
import { ArrowUpLeft, CalendarDays, Users, QrCode, Bell, Scissors, Stethoscope, Wrench, Building2, Check, ArrowLeft, Smartphone, Layers3 } from 'lucide-react';
import { MarketingShell, StartCTA } from '@/components/marketing/MarketingShell';
import { BookingDemo } from '@/components/marketing/BookingDemo';
import { PricingCards } from '@/components/marketing/PricingCards';
import { faqs } from '@/lib/marketing';
export default function HomePage(){return <MarketingShell><main id="main-content">
 <section className="mk-hero"><div className="mk-wrap mk-hero-grid"><div className="mk-hero-copy"><p className="mk-eyebrow"><span className="mk-dot"/> نوبت‌دهی آنلاین، به زبان خودتان</p><h1>نوبتِ شما،<br/><span>آرامشِ فردا.</span></h1><p className="mk-lead">مشتری از هرجا نوبت بگیرد.<br/>شما با خیال راحت به کارتان برسید.</p><p className="mk-hero-detail">از انتخاب روز و کارمند تا مدیریت صف و اطلاع‌رسانی؛ نوبتک، وقت شما و مشتریان‌تان را منظم می‌کند.</p><div className="mk-hero-actions"><Link href="/register" className="mk-btn">کسب‌وکارم را شروع می‌کنم <ArrowUpLeft size={19}/></Link><a href="#demo" className="mk-text-link">نمونه را امتحان کن <ArrowLeft size={18}/></a></div><div className="mk-hero-points"><span><Check size={15}/> بدون نصب برنامه</span><span><Check size={15}/> مناسب موبایل</span><span><Check size={15}/> تاریخ افغانستان</span></div></div><BookingDemo/></div><div className="mk-wrap mk-hero-bottom"><span>یک لینک برای مشتری؛ یک دید روشن برای شما.</span><span dir="ltr">NOBATAK / BUILT AROUND YOUR TIME</span></div></section>
 <section className="mk-industries"><div className="mk-wrap"><p>برای کسب‌وکارهایی که وقت مشتری برای‌شان مهم است</p><div>{[[Scissors,'آرایشگاه و زیبایی'],[Stethoscope,'کلینیک و مطب'],[Wrench,'تعمیرگاه و خدمات'],[Building2,'دفاتر و مجموعه‌ها']].map(([Icon,label])=>{const I=Icon as typeof Scissors;return <span key={String(label)}><I size={23}/>{String(label)}</span>})}</div></div></section>
 <section className="mk-wrap mk-section" id="features"><div className="mk-section-head"><div><p className="mk-eyebrow">یک همراه برای تمام روز</p><h2>صف را مدیریت کنید.<br/><span>نه نگرانی‌هایش را.</span></h2></div><Link href="/services" className="mk-text-link">همهٔ خدمات <ArrowUpLeft size={18}/></Link></div><div className="mk-feature-grid"><article className="mk-feature mk-feature-wide"><div><span className="mk-icon"><CalendarDays/></span><h3>هر روز، با برنامهٔ خودش</h3><p>روزهای پذیرش را مشخص کنید. اگر رخصت بودید، دلیلش را به مشتری نشان بدهید و اجازه بدهید روز دیگری انتخاب کند.</p></div><div className="mk-mini-week" aria-label="نمونهٔ تقویم پذیرش"><span>شنبه<b>باز</b></span><span>یک‌شنبه<b>باز</b></span><span className="closed">دوشنبه<b>رخصتی</b></span><span>سه‌شنبه<b>باز</b></span></div></article><article className="mk-feature mk-feature-blue"><span className="mk-icon"><Users/></span><h3>یک نگاه به تمام صف</h3><p>نوبت جاری، مشتریان منتظر و ظرفیت هر کارمند را در داشبورد ببینید.</p><div className="mk-queue-art" aria-hidden="true"><span>۰۱</span><span>۰۲</span><span>۰۳</span><ArrowLeft/></div></article><article className="mk-feature"><span className="mk-icon"><QrCode/></span><h3>راه کوتاه‌تر برای مشتری</h3><p>لینک اختصاصی یا کد QR را به اشتراک بگذارید؛ صفحهٔ نوبت‌گیری همیشه در دسترس مشتری است.</p></article><article className="mk-feature"><span className="mk-icon"><Bell/></span><h3>خبر نوبت، در تلگرام</h3><p>مشتری در صورت تمایل رسیدش را به تلگرام متصل می‌کند و پیام‌های نوبت را دریافت می‌کند.</p></article><article className="mk-feature"><span className="mk-icon"><Layers3/></span><h3>هر کارمند، ظرفیت خودش</h3><p>خدمات، مدت انجام و ظرفیت روزانه را متناسب با روش کار مجموعه تنظیم کنید.</p></article></div></section>
 <section className="mk-how"><div className="mk-wrap mk-how-grid"><div><p className="mk-eyebrow">از اولین لینک تا اولین نوبت</p><h2>پیچیده نیست.<br/>فقط سه قدم.</h2><Link href="/guide" className="mk-text-link">راهنمای کامل شروع <ArrowUpLeft size={18}/></Link></div><ol>{[['۰۱','کسب‌وکار خود را معرفی کنید','نام، خدمات و کارمندان را در حساب کسب‌وکار وارد کنید.'],['۰۲','لینک‌تان را به اشتراک بگذارید','لینک یا کد QR را به مشتریان بدهید. نصب برنامه لازم نیست.'],['۰۳','روزتان را منظم پیش ببرید','مشتری نوبت می‌گیرد و شما جریان صف را از داشبورد مدیریت می‌کنید.']].map(([n,title,text])=><li key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>
 <section className="mk-wrap mk-section" id="plans"><div className="mk-section-head mk-centered"><p className="mk-eyebrow">پلن‌های پیشنهادی</p><h2>هم‌اندازهٔ کسب‌وکار شما.</h2><p>یک طرح ساده برای شروع؛ فضایی برای رشد.</p></div><PricingCards/></section>
 <section className="mk-wrap mk-section mk-faq-grid"><div><p className="mk-eyebrow">قبل از شروع</p><h2>شاید سؤال<br/>شما هم باشد.</h2><Link href="/faq" className="mk-text-link">همهٔ پرسش‌ها <ArrowUpLeft size={18}/></Link><Smartphone className="mk-faq-icon" size={70} strokeWidth={1}/></div><div className="mk-faq">{faqs.slice(0,4).map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section><StartCTA/>
 </main></MarketingShell>}
