'use client';
import { useRef, useState } from 'react';
import { NavigationLink as Link } from '@/components/ui/NavigationLink';
export function ContactForm(){
 const lock=useRef(false);const request=useRef<{payload:string;id:string}|null>(null);
 const [pending,setPending]=useState(false);const [status,setStatus]=useState('');const [failed,setFailed]=useState(false);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(lock.current)return;lock.current=true;setPending(true);setStatus('');setFailed(false);const form=event.currentTarget;const data=new FormData(form);const payload=JSON.stringify({name:data.get('name'),email:data.get('email'),topic:data.get('topic'),message:data.get('message'),website:data.get('website')});if(request.current?.payload!==payload)request.current={payload,id:crypto.randomUUID()};
 try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(payload),requestId:request.current.id}),signal:AbortSignal.timeout(20000)});const result=await response.json();if(!response.ok)throw new Error(result.error||'ارسال پیام انجام نشد.');setStatus('پیام شما برای ارسال به پشتیبانی پذیرفته شد. پاسخ به ایمیل شما فرستاده خواهد شد.');form.reset();request.current=null;}catch(error){setFailed(true);setStatus(error instanceof Error&&error.name!=='TimeoutError'?error.message:'پاسخ ارسال دریافت نشد. دوباره تلاش کنید یا از واتساپ استفاده کنید.');}finally{lock.current=false;setPending(false);}}
 return <form className="mk-contact-form" onSubmit={submit}><h2>برای ما بنویسید</h2><p>پیام به <bdi>fahimullahrasty@gmail.com</bdi> ارسال می‌شود. اطلاعات حساس و گذرواژه را وارد نکنید.</p><fieldset disabled={pending} className="grid gap-5"><label>نام شما<input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="نام و نام خانوادگی"/></label><label>ایمیل برای دریافت پاسخ<input name="email" type="email" dir="ltr" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></label><label>موضوع<select name="topic"><option>پرسش دربارهٔ نوبتک</option><option>مشکل فنی</option><option>پیشنهاد و همکاری</option><option>حریم خصوصی و اطلاعات حساب</option></select></label><label>پیام شما<textarea name="message" rows={5} required minLength={10} maxLength={4000} placeholder="چطور می‌توانیم کمک کنیم؟"/></label><div hidden aria-hidden="true"><label>وب‌سایت<input name="website" tabIndex={-1} autoComplete="off"/></label></div><p>با ارسال پیام، اطلاعات این فرم برای پاسخ‌گویی استفاده می‌شود. <Link href="/privacy">حریم خصوصی</Link></p><button type="submit" className="mk-btn" disabled={pending} aria-busy={pending}>{pending?'در حال ارسال…':'ارسال پیام'}</button></fieldset>{status&&<p role={failed?'alert':'status'}>{status}</p>}{failed&&<a className="mk-text-link" href="mailto:fahimullahrasty@gmail.com">ارسال مستقیم با برنامهٔ ایمیل ←</a>}</form>;
}
