import { NavigationLink as Link } from '@/components/ui/NavigationLink';
import { ArrowUpLeft } from 'lucide-react';
import { MarketingNav } from './MarketingNav';
import { StorageNoticeLink } from './StorageNotice';
import '@/app/marketing.css';
export function MarketingShell({children}:{children:React.ReactNode}){
 return <div className="marketing"><a className="mk-skip" href="#main-content">رفتن به محتوای اصلی</a><MarketingNav/>{children}<footer className="mk-footer"><div className="mk-wrap"><div className="mk-footer-top"><div><Link href="/" className="mk-wordmark">نوبت<span>✦</span></Link><p>نوبت منظم‌تر، روز آرام‌تر.<br/>همراه کسب‌وکارها و مشتریان در افغانستان.</p></div><div><h2>نوبت</h2><Link href="/about">دربارهٔ ما</Link><Link href="/services">خدمات</Link><Link href="/pricing">پلن‌های نمونه</Link></div><div><h2>همراه شما</h2><Link href="/guide">راهنمای شروع</Link><Link href="/faq">پرسش‌های رایج</Link><Link href="/contact">تماس و پشتیبانی</Link><a href="https://wa.me/93780340446" target="_blank" rel="noopener noreferrer">واتساپ: <bdi>0780340446</bdi></a></div><div><h2>شفاف و روشن</h2><Link href="/privacy">حریم خصوصی</Link><Link href="/terms">شرایط استفاده</Link><StorageNoticeLink/></div></div><div className="mk-footer-bottom"><span>نوبت · برای احترام به وقت یکدیگر</span><Link href="/register">کسب‌وکارت را همراه کن <ArrowUpLeft size={16}/></Link></div></div></footer></div>;
}
export function PageIntro({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <header className="mk-page-intro"><div className="mk-wrap"><Link className="mk-breadcrumb" href="/">صفحهٔ اصلی /</Link><p className="mk-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div></header>;}
export function StartCTA(){return <section className="mk-wrap mk-cta"><div><p className="mk-eyebrow">نوبتِ یک شروع تازه</p><h2>وقت کمتر در صف.<br/>فرصت بیشتر برای زندگی.</h2></div><Link href="/register" className="mk-btn mk-btn-light">ساخت حساب کسب‌وکار <ArrowUpLeft size={20}/></Link></section>;}
