'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Modal } from '@/components/ui/Modal';
import { formatDate, formatMoney, methodLabels, paymentStatusLabels, remainingDays, statusLabels } from '@/lib/subscriptions';
import type { OwnerSubscription, PaymentMethod, PaymentStatus, SubscriptionPayment, SubscriptionPlan, SubscriptionStatus } from '@/types/database';

type OwnedBusiness = { id: string; name: string; slug: string; is_active: boolean; owner_id: string };
type OwnerRow = { id: string; full_name: string | null; phone: string | null; email: string | null; is_active: boolean; businesses: OwnedBusiness[] };
type Payload = { owners: OwnerRow[]; subscriptions: OwnerSubscription[]; payments: SubscriptionPayment[]; plans: SubscriptionPlan[]; conflicts: Array<{ owner_id: string; reason: string }>; setupRequired?: boolean; stats: { active: number; expiring: number; expired: number; paidCount: number; paidAmount: number } };
type Filter = 'all' | 'active' | 'expiring' | 'expired' | 'unpaid' | 'suspended';
type GraphRange = '7d' | '30d' | '6m' | '1y';
const inputClass = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900';

function FinanceGraph({ payments, owners }: { payments: SubscriptionPayment[]; owners: OwnerRow[] }) {
  const [range, setRange] = useState<GraphRange>('30d');
  const [referenceNow] = useState(() => Date.now());
  const rows = useMemo(() => {
    const days = range === '7d' ? 7 : range === '30d' ? 30 : range === '6m' ? 183 : 365; const cutoff = referenceNow - days * 86400000; const byOwner = new Map(owners.map(owner => [owner.id, owner.full_name || 'بدون نام'])); const buckets = new Map<string, { amount: number; payments: SubscriptionPayment[] }>();
    for (const payment of payments) { const stamp = payment.paid_at || payment.created_at; if (payment.payment_status !== 'paid' || Date.parse(stamp) < cutoff) continue; const date = new Date(stamp); const key = range === '6m' || range === '1y' ? `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}` : stamp.slice(0, 10); const bucket = buckets.get(key) || { amount: 0, payments: [] }; bucket.amount += Number(payment.amount); bucket.payments.push(payment); buckets.set(key, bucket); }
    return [...buckets.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => ({ key, ...value, tooltip: value.payments.map(payment => `${formatDate(payment.paid_at || payment.created_at)} — ${formatMoney(payment.amount, payment.currency)} — ${byOwner.get(payment.owner_id)} — ${payment.plan_code}`).join('\n') }));
  }, [owners, payments, range, referenceNow]);
  const max = Math.max(1, ...rows.map(row => row.amount)); const total = rows.reduce((sum, row) => sum + row.amount, 0);
  return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black text-white">نمودار درآمد واقعی</h2><p className="mt-1 text-xs text-slate-400">فقط پرداخت‌های تأییدشده · مجموع بازه: {formatMoney(total)}</p></div><div className="flex rounded-xl bg-slate-950 p-1">{([['7d', '۷ روز'], ['30d', '۳۰ روز'], ['6m', '۶ ماه'], ['1y', '۱ سال']] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setRange(value)} className={`rounded-lg px-3 py-2 text-xs font-bold ${range === value ? 'bg-blue-600 text-white' : 'text-slate-400 hover:text-white'}`}>{label}</button>)}</div></div>{rows.length ? <div className="mt-6 flex h-56 items-end gap-2 overflow-x-auto border-b border-slate-700 pb-2" aria-label="نمودار درآمد">{rows.map(row => <div key={row.key} className="flex min-w-12 flex-1 flex-col items-center justify-end gap-2" title={row.tooltip}><span className="text-[10px] text-slate-400">{Number(row.amount).toLocaleString('fa-AF')}</span><div className="w-full rounded-t-lg bg-gradient-to-t from-blue-700 to-cyan-400" style={{ height: `${Math.max(8, row.amount / max * 160)}px` }} /><span className="text-[10px] text-slate-500">{row.key}</span></div>)}</div> : <p className="mt-6 rounded-xl bg-slate-950/60 p-8 text-center text-sm text-slate-400">در این بازه پرداخت تأییدشده‌ای وجود ندارد.</p>}</section>;
}

export default function SubscriptionsPage() {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<Filter>('all'); const [selected, setSelected] = useState<OwnerRow | null>(null);
  const [formOpen, setFormOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [referenceNow] = useState(() => Date.now());
  const today = new Date().toISOString().slice(0, 10);
  const [form, setForm] = useState({ planCode: 'growth', amount: '490', currency: 'AFN', method: 'cash' as PaymentMethod, customMethod: '', status: 'paid' as PaymentStatus, paidAt: today, startAt: today, durationMonths: '1', customEndAt: '', reference: '', note: '', maxBusinesses: '', unlimitedBusinesses: false, maxServices: '', maxStaff: '', maxDaily: '', workShifts: true, maxShifts: '2', telegramNotifications: true });
  const load = useCallback(async () => { setLoading(true); setError(''); const response = await fetch('/api/admin/subscriptions', { cache: 'no-store' }); const body = await response.json(); if (!response.ok) setError(body.error || 'خطا در دریافت اطلاعات'); else setData(body); setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const subscriptionFor = useCallback((id: string) => data?.subscriptions.find(item => item.owner_id === id), [data]);
  const paymentsFor = useCallback((id: string) => data?.payments.filter(item => item.owner_id === id) ?? [], [data]);
  const effective = useCallback((sub?: OwnerSubscription) => !sub ? 'expired' : sub.status === 'active' && sub.expires_at && Date.parse(sub.expires_at) <= referenceNow ? 'expired' : sub.status, [referenceNow]);
  const maxBusinesses = useCallback((sub?: OwnerSubscription) => { if (!sub) return 1; const custom = sub.custom_limits as Record<string, unknown>; const plan = data?.plans.find(item => item.code === sub.plan_code); const defaults = plan?.limits as Record<string, unknown> | undefined; const value = custom?.max_businesses ?? defaults?.max_businesses; return value === null ? null : Number(value ?? 1); }, [data]);
  const visible = useMemo(() => (data?.owners ?? []).filter(owner => {
    const sub = subscriptionFor(owner.id); const state = effective(sub); const days = remainingDays(sub?.expires_at ?? null); const text = `${owner.full_name ?? ''} ${owner.phone ?? ''} ${owner.email ?? ''} ${owner.businesses.map(item => item.name).join(' ')}`.toLowerCase();
    if (!text.includes(query.trim().toLowerCase())) return false;
    if (filter === 'active') return state === 'active'; if (filter === 'expiring') return state === 'active' && days !== null && days <= 7;
    if (filter === 'expired') return state === 'expired'; if (filter === 'unpaid') return !paymentsFor(owner.id).some(p => p.payment_status === 'paid'); if (filter === 'suspended') return state === 'suspended'; return true;
  }), [data, effective, filter, paymentsFor, query, subscriptionFor]);
  const openPayment = (owner: OwnerRow) => { const plan = data?.plans.find(p => p.code === 'growth'); setSelected(owner); setForm(previous => ({ ...previous, amount: String(plan?.default_amount ?? 490), startAt: today, paidAt: today })); setFormOpen(true); };
  const changePlan = (code: string) => { const plan = data?.plans.find(p => p.code === code); const limits = (plan?.limits || {}) as Record<string, unknown>; setForm(previous => ({ ...previous, planCode: code, amount: plan?.default_amount === null ? previous.amount : String(plan?.default_amount ?? previous.amount), durationMonths: plan?.duration_months ? String(plan.duration_months) : previous.durationMonths, maxBusinesses: String(limits.max_businesses ?? previous.maxBusinesses), unlimitedBusinesses: limits.max_businesses === null, maxServices: String(limits.max_services ?? previous.maxServices), maxStaff: String(limits.max_staff ?? previous.maxStaff), maxDaily: String(limits.max_daily_appointments ?? previous.maxDaily), workShifts: limits.work_shifts_enabled === undefined ? previous.workShifts : limits.work_shifts_enabled === true, maxShifts: String(limits.max_work_shifts ?? previous.maxShifts), telegramNotifications: limits.telegram_notifications === undefined ? previous.telegramNotifications : limits.telegram_notifications === true })); };
  const submitPayment = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; setSaving(true); setError('');
    const customLimits = form.planCode === 'custom' ? { max_businesses: form.unlimitedBusinesses ? null : Number(form.maxBusinesses || 1), max_services: Number(form.maxServices || 3), max_staff: Number(form.maxStaff || 1), max_daily_appointments: Number(form.maxDaily || 10), advanced_scheduling: true, work_shifts_enabled: form.workShifts, max_work_shifts: Number(form.maxShifts || 0), telegram_notifications: form.telegramNotifications } : {};
    const response = await fetch('/api/admin/subscriptions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'payment', ownerId: selected.id, ...form, durationMonths: form.customEndAt ? null : form.durationMonths, customEndAt: form.customEndAt || null, customLimits }) }); const body = await response.json();
    if (!response.ok) setError(body.error || 'ثبت پرداخت انجام نشد.'); else { setFormOpen(false); await load(); } setSaving(false);
  };
  const setStatus = async (ownerId: string, status: 'active' | 'suspended' | 'cancelled') => { const reason = status === 'active' ? '' : window.prompt('دلیل تغییر وضعیت (اختیاری):') || ''; const response = await fetch('/api/admin/subscriptions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'status', ownerId, status, reason }) }); const body = await response.json(); if (!response.ok) setError(body.error); else await load(); };
  const editPayment = async (payment: SubscriptionPayment, cancel = false) => { const reference = cancel ? payment.reference_number : window.prompt('شماره مرجع:', payment.reference_number || '') ?? payment.reference_number; const note = cancel ? payment.note : window.prompt('یادداشت:', payment.note || '') ?? payment.note; const status = cancel ? 'cancelled' : payment.payment_status; const response = await fetch('/api/admin/subscriptions', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paymentId: payment.id, method: payment.payment_method, customMethod: payment.custom_payment_method, reference, note, status }) }); const body = await response.json(); if (!response.ok) setError(body.error); else await load(); };

  if (loading) return <p className="text-slate-300">در حال دریافت اطلاعات مالی…</p>;
  return <div className="space-y-6">
    <div><h1 className="text-2xl font-black text-white">اشتراک صاحبان کسب‌وکار</h1><p className="mt-1 text-sm text-slate-400">هر صاحب حساب یک اشتراک دارد و تمام کسب‌وکارهایش همان پلن را به ارث می‌برند.</p></div>
    {error && <div role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-200">{error}</div>}
    {data?.setupRequired && <div role="alert" className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm leading-7 text-amber-100">ساختار مالی جدید هنوز روی Supabase نصب نشده است. اطلاعات فعلی از پروفایل‌ها به‌صورت فقط‌خواندنی نمایش داده می‌شود؛ برای ثبت پرداخت و تمدید، فایل <code dir="ltr" className="rounded bg-slate-950 px-1.5 py-0.5">supabase/manual_subscriptions.sql</code> را در SQL Editor پروژه اجرا کنید.</div>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['اشتراک فعال', data?.stats.active], ['نزدیک انقضا', data?.stats.expiring], ['منقضی', data?.stats.expired], ['پرداخت ماه', data?.stats.paidCount], ['درآمد ماه', formatMoney(data?.stats.paidAmount ?? 0)]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-xl font-black text-white">{value}</p></div>)}</div>
    <FinanceGraph payments={data?.payments ?? []} owners={data?.owners ?? []} />
    <div className="grid gap-3 rounded-2xl border border-slate-800 bg-slate-900 p-4 md:grid-cols-[1fr_auto]">
      <Input aria-label="جست‌وجو" placeholder="نام کسب‌وکار، مالک، تلفن یا نشانی…" value={query} onChange={e => setQuery(e.target.value)} />
      <select aria-label="فیلتر اشتراک" className={inputClass} value={filter} onChange={e => setFilter(e.target.value as Filter)}><option value="all">همه</option><option value="active">فعال</option><option value="expiring">تا ۷ روز مانده</option><option value="expired">منقضی</option><option value="unpaid">بدون پرداخت</option><option value="suspended">تعلیق</option></select>
    </div>
    <div className="space-y-4">{visible.map(owner => { const sub = subscriptionFor(owner.id); const state = effective(sub) as SubscriptionStatus; const history = paymentsFor(owner.id); const days = remainingDays(sub?.expires_at ?? null); const limit = maxBusinesses(sub); const conflict = data?.conflicts.some(item => item.owner_id === owner.id); return <article key={owner.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-bold text-white">{owner.full_name || 'صاحب حساب بدون نام'}</h2><p className="text-xs text-slate-400">{owner.phone || 'بدون تلفن'} · {owner.email || 'ایمیل ثبت نشده'}</p>{conflict && <p className="mt-2 text-xs font-bold text-rose-300">اشتراک‌های قدیمی متعارض‌اند؛ بررسی دستی لازم است.</p>}</div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-800 px-3 py-1 text-xs text-slate-200">{sub?.plan_code || 'free'}</span><span className={`rounded-full px-3 py-1 text-xs ${state === 'active' ? 'bg-emerald-500/15 text-emerald-300' : 'bg-amber-500/15 text-amber-300'}`}>{statusLabels[state]}</span></div></div>
      <div className="mt-4 grid gap-2 text-sm text-slate-300 sm:grid-cols-4"><p>شروع: {formatDate(sub?.started_at ?? null)}</p><p>پایان: {formatDate(sub?.expires_at ?? null)}</p><p>مانده: {days === null ? 'نامحدود' : `${days.toLocaleString('fa-AF')} روز`}</p><p>کسب‌وکار: {owner.businesses.length.toLocaleString('fa-AF')} از {limit === null ? 'نامحدود' : limit.toLocaleString('fa-AF')}</p></div>
      <details className="mt-3 rounded-xl bg-slate-950/50 p-3"><summary className="cursor-pointer text-sm font-bold text-slate-200">کسب‌وکارهای این مالک</summary><ul className="mt-2 space-y-1 text-xs text-slate-400">{owner.businesses.length ? owner.businesses.map(item => <li key={item.id}>{item.name} — {item.is_active ? 'فعال' : 'غیرفعال'}</li>) : <li>هنوز کسب‌وکاری ثبت نشده است.</li>}</ul></details>
      <div className="mt-4 flex flex-wrap gap-2"><Button disabled={data?.setupRequired} onClick={() => openPayment(owner)}>ثبت پرداخت / تمدید / تغییر پلن</Button>{state !== 'suspended' && <Button disabled={data?.setupRequired} variant="secondary" onClick={() => void setStatus(owner.id, 'suspended')}>تعلیق اشتراک</Button>}{state === 'suspended' && <Button disabled={data?.setupRequired} variant="secondary" onClick={() => void setStatus(owner.id, 'active')}>فعال‌سازی</Button>}{state !== 'cancelled' && <Button disabled={data?.setupRequired} variant="danger" onClick={() => void setStatus(owner.id, 'cancelled')}>لغو اشتراک</Button>}</div>
      <details className="mt-4 border-t border-slate-800 pt-3"><summary className="cursor-pointer text-sm font-bold text-slate-200">تاریخچه پرداخت ({history.length.toLocaleString('fa-AF')})</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[800px] text-right text-xs"><thead className="text-slate-500"><tr><th className="p-2">تاریخ</th><th>مبلغ</th><th>روش</th><th>وضعیت</th><th>دوره</th><th>مرجع / یادداشت</th><th>عملیات</th></tr></thead><tbody>{history.map(payment => <tr key={payment.id} className="border-t border-slate-800 text-slate-300"><td className="p-2">{formatDate(payment.paid_at || payment.created_at)}</td><td>{formatMoney(payment.amount, payment.currency)}</td><td>{payment.payment_method === 'other' ? payment.custom_payment_method : methodLabels[payment.payment_method]}</td><td>{paymentStatusLabels[payment.payment_status]}</td><td>{formatDate(payment.subscription_start_at)} تا {formatDate(payment.subscription_end_at)}</td><td>{payment.reference_number || payment.note || '—'}</td><td><button className="text-blue-300 underline" onClick={() => void editPayment(payment)}>ویرایش جزئیات</button>{payment.payment_status !== 'paid' && payment.payment_status !== 'cancelled' && <button className="mr-3 text-rose-300 underline" onClick={() => void editPayment(payment, true)}>لغو نرم</button>}</td></tr>)}</tbody></table></div></details>
    </article>; })}</div>
    <Modal isOpen={formOpen} onClose={() => !saving && setFormOpen(false)} title={`ثبت پرداخت برای ${selected?.full_name ?? 'صاحب حساب'}`} className="max-w-3xl"><form className="grid gap-4 sm:grid-cols-2" onSubmit={submitPayment}>
      <label className="text-xs font-bold text-slate-700">پلن<select className={`${inputClass} mt-1`} value={form.planCode} onChange={e => changePlan(e.target.value)}>{data?.plans.filter(plan => ['free', 'growth', 'custom'].includes(plan.code)).map(plan => <option key={plan.code} value={plan.code}>{plan.name}</option>)}</select></label>
      <Input label="مبلغ" type="number" min="0" step="0.01" required value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} />
      <Input label="واحد پول" maxLength={3} required value={form.currency} onChange={e => setForm({ ...form, currency: e.target.value.toUpperCase() })} />
      <label className="text-xs font-bold text-slate-700">روش پرداخت<select className={`${inputClass} mt-1`} value={form.method} onChange={e => setForm({ ...form, method: e.target.value as PaymentMethod })}>{Object.entries(methodLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      {form.method === 'other' && <Input label="نام روش دیگر" required value={form.customMethod} onChange={e => setForm({ ...form, customMethod: e.target.value })} />}
      <label className="text-xs font-bold text-slate-700">وضعیت پرداخت<select className={`${inputClass} mt-1`} value={form.status} onChange={e => setForm({ ...form, status: e.target.value as PaymentStatus })}>{Object.entries(paymentStatusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      <Input label="تاریخ پرداخت" type="date" required={form.status === 'paid'} value={form.paidAt} onChange={e => setForm({ ...form, paidAt: e.target.value })} />
      <Input label="شروع اشتراک" type="date" required value={form.startAt} onChange={e => setForm({ ...form, startAt: e.target.value })} />
      <label className="text-xs font-bold text-slate-700">مدت<select className={`${inputClass} mt-1`} value={form.durationMonths} disabled={Boolean(form.customEndAt)} onChange={e => setForm({ ...form, durationMonths: e.target.value })}>{[1, 3, 6, 12].map(month => <option key={month} value={month}>{month.toLocaleString('fa-AF')} ماه</option>)}</select></label>
      <Input label="پایان سفارشی (اختیاری)" type="date" value={form.customEndAt} onChange={e => setForm({ ...form, customEndAt: e.target.value })} />
      <Input label="شماره مرجع" value={form.reference} onChange={e => setForm({ ...form, reference: e.target.value })} />
      <Input label="یادداشت" value={form.note} onChange={e => setForm({ ...form, note: e.target.value })} />
      {form.planCode === 'custom' && <><Input label="حد کسب‌وکار" type="number" min="1" disabled={form.unlimitedBusinesses} value={form.maxBusinesses} onChange={e => setForm({ ...form, maxBusinesses: e.target.value })} /><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={form.unlimitedBusinesses} onChange={e => setForm({ ...form, unlimitedBusinesses: e.target.checked })} />تعداد کسب‌وکار نامحدود</label><Input label="حد خدمات برای هر کسب‌وکار" type="number" min="1" value={form.maxServices} onChange={e => setForm({ ...form, maxServices: e.target.value })} /><Input label="حد کارمند برای هر کسب‌وکار" type="number" min="1" value={form.maxStaff} onChange={e => setForm({ ...form, maxStaff: e.target.value })} /><Input label="حد نوبت روزانه برای هر کسب‌وکار" type="number" min="1" value={form.maxDaily} onChange={e => setForm({ ...form, maxDaily: e.target.value })} /><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={form.workShifts} onChange={e => setForm({ ...form, workShifts: e.target.checked })} />شیفت کاری فعال باشد</label><Input label="حد شیفت برای هر کسب‌وکار" type="number" min="0" disabled={!form.workShifts} value={form.maxShifts} onChange={e => setForm({ ...form, maxShifts: e.target.value })} /><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={form.telegramNotifications} onChange={e => setForm({ ...form, telegramNotifications: e.target.checked })} />اطلاع‌رسانی تلگرام فعال باشد</label></>}
      <div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={saving}>{saving ? 'در حال ثبت…' : 'ثبت در تاریخچه'}</Button><Button type="button" variant="secondary" onClick={() => setFormOpen(false)}>انصراف</Button></div>
    </form></Modal>
  </div>;
}
